version: "3.9"
services:
  analysis:
      image: jupyter/scipy-notebook
      ports:
        - "8888:8888"
      volumes:
        - .:/home/jovyan/milestone-1
      environment:
        - JUPYTER_ENABLE_LAB=yes